### ISSUE TITLE
Alias Success#fold / Failure#fold as reduce for fantasy-land compliance

### ISSUE THREAD

**Issue by jimf** [folktale/data.validation#12]
This is partially a question. Would it make sense to make `reduce` aliases for `Success#fold` and `Failure#fold` for [fantasy-land foldable compliance](https://github.com/fantasyland/fantasy-land#foldable)? I'd be happy to make the PR; just wanted a gut-check first.

**Comment by robotlolita** [comment]
Hm, I don't think Validation (or Either) make much sense as a Foldable, because you'd basically get: `Success.of(x).toArray() === [x]` and `Failure.of(x).toArray() === []`. It's always a one-element array.

The `fold` name here is more in line with the broarder concept of catamorphism, where it basically allows you to define a function for each case in the algebra.

**Comment by jimf** [comment]
Yeah, that makes sense. I was playing with it more in a repl and really starting to doubt myself. Cross-checked [fantasy-validations](https://github.com/fantasyland/fantasy-validations/blob/430479014b0e7bfd2355137bce8f21ae7226d78b/src/validation.js#L14-L19) for the heck of it, and doing so validates your explanation even further. Thanks!
