### ISSUE TITLE
No chain?

### ISSUE THREAD

**Issue by ebsi-cgoboncan** [folktale/data.validation#15]
the docs say validation implements chain, but it is not implemented.

**Comment by robotlolita** [comment]
Ah, the docs are outdated. I'm sorry.

See https://github.com/folktale/data.validation/issues/1 for why Validation can't implement Chain or Monad

**Comment by ebsi-cgoboncan** [comment]
I'm not sure I follow the logic in #1. If x is Failure, then case one would return noop as well as case two. If y is Failure then you would have the same result. Also, this example of a result monad in F# [link](https://fsharpforfunandprofit.com/posts/recipe-part2/) most definitely implements chain/bind.

**Comment by robotlolita** [comment]
The F# example in that link doesn't implement applicative Validations, they're equivalent to https://github.com/folktale/data.either instead, which does provide both `.ap` and `.chain`.

## Why Data.Validation?

So, what's the problem with Data.Validation in particular? The problem is that `.ap` is not a no-op when you have failures in Data.Validation, instead it does _error aggregation_. This is the important distinction between Data.Validation and Data.Either, as otherwise they're pretty much the same data structure.

Let's consider a simple example to see this in action:

``` js
// We have some validations
const errorA = Validation.Failure(["A"]);
const errorB = Validation.Failure(["B"]);
const value = Validation.Success(1);
```

If we start from a success, and apply an error, we get an error, as expected:

``` js
Validation.of(x => x + 1).ap(errorA);
// ==> Validation.Failure(["A"])

Validation.of(x => x + 1).ap(errorB);
// ==> Validation.Failure(["B"]);
```

If we start from a success, and apply a success, then we run the function in the first validation over the value in the second validation. Also as expected:

``` js
Validation.of(x => x + 1).ap(value)
// ==> Validation.Success(2)
```

Until here, Data.Validation works exactly like Data.Either. The difference comes when we try to apply to errors together:

``` js
Validation.of(x => x + 1).ap(errorA).ap(errorB);
// ==> Validation.Failure(["A", "B"])
```

What happens here is that when you apply two failures together, you get a new failure that's the concatenation of the values in both validations! In essence, the behaviour you're seeing is the following:

``` js
Validation.Failure(["A"]).ap(Validation.Failure(["B"])
=== Validation.Failure(["A"].concat(["B"]))
=== Validation.Failure(["A", "B"])
```

This works as long as the validation on the left side provides a `concat` method conforming to [Semigroup](https://github.com/fantasyland/fantasy-land#semigroup)

But why is this useful? Well, when you're doing validations in a data structure you have two options:

1) fail at the first error and return that, without evaluating anything else. This is what Data.Either does.
2) evaluate everything, and aggregate all of the failures that you encounter. This is what Data.Validation does.

The second approach is much more useful when you're validating things like Form inputs, for example. You don't want to show the user just the first failure, you want to show them all of the things that are wrong with the form, so the user can fix them all and click `submit` again. This is trivial with Data.Validation:

``` js
const required = (field, form) =>
  form[field] === ''
  ? Validation.Failure([`${field}  is a required field.`])
  : Validation.Success(form[field]);

form = { username: '', password: '123456', email: '' };

Validation.of(username => password => email => ({ username, password, email }))
.ap(required('username', form))
.ap(required('password', form))
.ap(required('email', form))
// ==> Validation.Failure([
//  "username is a required field.", 
//  "email is a required field."
// ])
```

If you had Data.Either, you'd get this instead:

``` js
const required = (field, form) =>
  form[field] === ''
  ? Either.Left([`${field}  is a required field.`])
  : Either.Right(form[field]);

form = { username: '', password: '123456', email: '' };

Either.of(username => password => email => ({ username, password, email }))
.ap(required('username', form))
.ap(required('password', form))
.ap(required('email', form));
// ==> Either.Left(["username is a required field."])
```

## Why can't we have `.chain` in Data.Validation?

As you can see, Data.Validation does error aggregation when you apply, but how does this prevent Data.Validation from having a Monad instance? Well, that's what Brian explains in the issue linked. From Brian's example:

> If validation were a monad, the following two expressions would be equal:
> 
> ``` js
> x.map(function(a) {
>  return function(b) {
>    return [a, b];
>  };
> }).ap(y);
> 
> x.chain(function(a) {
>  return y.map(function(b) {
>    return [a, b];
>  });
> });
> ```
> 
> It's not possible to make those be equal in the case that both x and y are failures.

An implementation of `.chain` for Data.Validation would look like this:

``` js
Validation.prototype.chain = function(f) {
  return this.cata({
    Failure: x => Validation.Failure(x),
    Success: x => f(x)
  });
}
```

So let's look at how these are evaluated to try and understand this assertion. First, let's pick some random `x`s and `y`s:

``` js
const x = Validation.Failure(["A"]);
const y = Validation.Failure(["B"]);
const z = Validation.Success(1);
```

If we start from `x` and move to `z`, then the behaviour is consistent in the two examples:

``` js
x.map(a => b => [a, b]).ap(z);
// ==> Validation.Failure(["A"])

x.chain(a => z.map(b => [a, b]));
// ==> Validation.Failure(["A"])
```

So far so good, both give us the same result. The same is also true if we only have successes:

``` js
z.map(a => b => [a, b]).ap(z);
// ==> Validation.Success([1, 1])

z.chain(a => z.map(b => [a, b]));
// ==> Validation.Success([1, 1])
```

But what happens if you have two failures? Well, then things don't look so good anymore:

``` js
x.map(a => b => [a, b]).ap(y);
// ==> Validation.Failure(["A", "B"])

x.chain(a => y.map(b => [a, b]));
// ==> Validation.Failure(["A"])
```

Note that `ap` returns one result (the aggregation of all errors), but `chain` returns another result (the first error). `chain` can't really do anything _else_ in this case because it never receives the other Validation as argument! And this, seemingly trivial difference, would cause all sorts of issues when you start composing Validations sometimes-as-monads, sometimes-as-applicatives. That's why Validation doesn't provide a Monad instance.

I hope that's easy to follow. If you don't understand any part of it, just ask :)

**Comment by ebsi-cgoboncan** [comment]
Thanks for the explanation.

Just to clarify, I believe the F# example is equivalent  to Validation, and he does implement applicative validation (he just calls it plus in the example, albeit this semigroup is a string, not a list).

``` javascript
let plus switch1 switch2 x = 
    match (switch1 x),(switch2 x) with
    | Success s1,Success s2 -> Success (s1 + s2)
    | Failure f1,Success _  -> Failure f1
    | Success _ ,Failure f2 -> Failure f2
    | Failure f1,Failure f2 -> Failure (f1 + f2)
```

So after looking at Brian's example again, I think I see the problem with the logic. 

Is 

``` javascript
x.chain(a => y.map(b => [a, b]))
```

 supposed to be ap implemented in terms of chain and map? Then shouldn't the function be

``` javascript
x.map(a => b => [a, b]).chain(a => y.map(a))
```

?

Also, I thought that while ap can be implemented in terms of bind and map, if it doesn't adhere to the monadic or applicative laws, then the implementation is incorrect. But this does not exclude it from being a monad since we can correctly implement bind and return.

Lastly, and this maybe just my opinion, when I use chain and a monadic style, I would expect the first failure from a chain to short circuit the rest (just like in all monads). If I use ap and the applicative style, then I would expect all failures to be aggregated together.

**Comment by robotlolita** [comment]
`plus` is not an `Applicative` there. Applicative has the following type:

``` hs
ap :: (Applicative f) => (f (a -> b)) -> f a -> f b
ap this that = ...
```

In Folktale, this means that the `this` argument (in `this.ap(that)`) has to be an Applicative containing a function from some type (which we call `a`), to another type (which we call `b`). Then, the operation requires a `that` argument, of type `Applicative a`, and returns an `Applicative b`.

If we make this type specific for the `Validation` applicative, we get the following:

``` hs
ap :: Validation (a -> b) -> Validation a -> Validation b
```

Meanwhile, the type for `plus` is:

``` hs
plus : (a -> Validation (Semigroup b)) -> (a -> Validation (Semigroup b)) -> a -> Validation (Semigroup b)
```

Which is a very different type. In the case of `plus`, it expects both `Success` and `Failure` to be values containing a semigroup, it then concatenates the semigroups if you have two of the same type.

We can compare the implementation of both:

``` fsharp
let plus this that = match this, that with
  | Success s1, Success s2 = Success (s1 + s2)
  | Failure f1, Failure f2 = Failure (f1 + f2)
  | Failure f, _ = Failure f
  | _, Failure f = Failure f

let ap this that = match this, that with
  | Success f, Success x = fmap x f
  | Failure f1, Failure f2 = Failure (f1 + f2)
  | Failure f, _ = Failure f
  | _, Failure f = Failure f

// fmap is the Functor's map
let fmap container transform = match container with
  | Success value = Success (transform value)
  | Failure value = Failure value
```

Note that what `plus` and `ap` do when you have two successes is very different.

---

You must be able to implement `ap` when you have `Monad`. In these cases, the behaviour of `ap` is defined as:

``` js
function ap(x){ return this.chain(f => x.map(f)) }
```

That is, the object on which you call `.chain` is expected to contain a function, and you must return a value of the same type but with the contents transformed by said function, so you run it through the provided value's `.map`. See https://github.com/fantasyland/fantasy-land#monad for details.

---

Sure, you can implement `Monad` that's correct on its own, and `Applicative` that's correct on its own for Validation, but this is a huge problem when you start composing things. If something uses `chain` _and_ `ap`, you get entirely unpredictable results! One of the points of Folktale is to add predictability when composing operations, and this is what a specification like Fantasy Land aims to address.

Because of this, `chain` won't be added to Applicative. It leads to confusing and unpredictable behaviour. You can still use `Data.Either` if you want fail-fast monadic behaviour, of course.

**Comment by vendethiel** [comment]
> plus is not an Applicative there. Applicative has the following type:
> ap :: (Applicative f) => (f a -> b) -> f a -> f b
> ap this that = ...

Should be `f (a -> b)`.

**Comment by robotlolita** [comment]
@vendethiel ah yeah. Thanks :)
